// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfteSTSyCrEXxPwcxOOMftKs94DdaP8WM',
    appId: '1:623373387128:web:385726dc2b2df40476348d',
    messagingSenderId: '623373387128',
    projectId: 'notesapp-by-alex',
    authDomain: 'notesapp-by-alex.firebaseapp.com',
    storageBucket: 'notesapp-by-alex.appspot.com',
    measurementId: 'G-9HL28DX7LH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNxF4zYCc-1KqDTp_Gz11pbl_-CfpQdLo',
    appId: '1:623373387128:android:c8b933a35ee8fb8176348d',
    messagingSenderId: '623373387128',
    projectId: 'notesapp-by-alex',
    storageBucket: 'notesapp-by-alex.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGtwpO6oeiG585-ijXO-NRxMYlz8im90Y',
    appId: '1:623373387128:ios:a06d4ebf3291ddb276348d',
    messagingSenderId: '623373387128',
    projectId: 'notesapp-by-alex',
    storageBucket: 'notesapp-by-alex.appspot.com',
    iosClientId: '623373387128-945rb2gqr1h66tiijetuu427knmcb56u.apps.googleusercontent.com',
    iosBundleId: 'com.myFirstApp.notesapp',
  );
}
